<a href="https://colab.research.google.com/github/SenseiGong/SenseiGong/blob/main/Corso%20Avanzato%20Python%2014-17%20aprile%202025_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Ciao Mondo")

Ciao Mondo


In [6]:
family=['Gionata', 1.71, 'Samuele', 1.78, 'Tommaso', 1.69]
print(family[0])
print(family[0:3])
print(family[:6])

Gionata
['Gionata', 1.71, 'Samuele']
['Gionata', 1.71, 'Samuele', 1.78, 'Tommaso', 1.69]


In [19]:
family=[['Gionata', 1.71], ['Samuele', 1.78], ['Tommaso', 1.69]]

print(family[0])
print(family[1])
print(family[:6])

['Gionata', 1.71]
['Samuele', 1.78]
[['Gionata', 1.71], ['Samuele', 1.78], ['Tommaso', 1.69]]


In [28]:
bro='Tommaso'
bro.replace('mm','X')
print(bro)

Tommaso


In [29]:
altezza=[1.71,1.68,1.80]
peso=[83, 65, 85]
peso / altezza ** 2
non va

SyntaxError: invalid syntax (<ipython-input-29-a52c817a338f>, line 4)

In [40]:
import numpy as np
altezza = np.altezza=[1.71,1.68,1.80]
peso = np.peso=[83.4, 65.3, 85.8]

bmi = peso / (altezza ** 2)
return bmi

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [41]:
import numpy as np

def calcola_bmi(peso, altezza):
  """
  Calcola il Body Mass Index (BMI).

  Args:
    peso: Un array NumPy o una lista di pesi in chilogrammi.
    altezza: Un array NumPy o una lista di altezze in metri.

  Returns:
    Un array NumPy o una lista di valori BMI.
  """
  # Converti peso e altezza in array NumPy se non lo sono già
  peso = np.array(peso)
  altezza = np.array(altezza)

  # Calcola il BMI
  bmi = peso / (altezza ** 2)

  return bmi

# Dati di esempio
altezza = [1.71, 1.68, 1.80]
peso = [83, 65, 85]

# Calcola il BMI
bmi_values = calcola_bmi(peso, altezza)

# Stampa i risultati
for i, bmi in enumerate(bmi_values):
  print(f"Persona {i+1}: BMI = {bmi:.2f}")

Persona 1: BMI = 28.38
Persona 2: BMI = 23.03
Persona 3: BMI = 26.23


In [52]:
myarray=np.arange(12).reshape((3,4))
myarray [: , :]
myarray[:, 0:2]
myarray[:, 1]
dummy=myarray.copy()
dummy[0,:]=-999
dummy[:,1]=[100,200,300]
dummy

array([[-999,  100, -999, -999],
       [   4,  200,    6,    7],
       [   8,  300,   10,   11]])

In [58]:
dummy=np.arange(-10,10).reshape((4,5))
dummy
mask=dummy>5
mask
dummy[mask]


array([6, 7, 8, 9])

In [61]:
x= np.array([56, 13,2, 8, 12])
print(np.sort(x))
condition= np.where(x>5, True, False)
condition

[ 2  8 12 13 56]


array([ True,  True, False,  True,  True])

In [75]:
A=np.ones((2,3))
print(A)
A=A*2
A=A**3
A

[[1. 1. 1.]
 [1. 1. 1.]]


array([[8., 8., 8.],
       [8., 8., 8.]])

In [89]:
A=np.ones((2,3))
print(A)
B= A*2
print(B)
C=np.add(B,A)
print(C)
D=np.multiply(A,B,out=np.zeros((2,3), where[[True, True, True], [False, False, False]]))
D

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[3. 3. 3.]
 [3. 3. 3.]]


NameError: name 'where' is not defined

In [92]:
dummy=np.ones((4,3,2))
dummy

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [99]:
dummy=np.ones((4,3,2))
dummy.sum(axis=0)
dummy.sum()
dummy.sum(axis=1)
dummy.sum(axis=1).shape

(4, 2)

Conditional Functions


In [106]:
A=np.full((2,3),4)
print(A)
B=np.full_like(A,-10)
print(B)
C=np.arange(6).reshape(2,3)
C
np.where(C>3, A ,B)


[[4 4 4]
 [4 4 4]]
[[-10 -10 -10]
 [-10 -10 -10]]


array([[-10, -10, -10],
       [-10,   4,   4]])

Broadcasting